### PR TITLE
Addon-Docs: Avoid rerendering static Source blocks

### LINKED ISSUE #23776: [Bug]: Performance regression when using many Source components in one mdx page
### Describe the bug

We got a report that when using the Source component:
https://storybook.js.org/docs/react/api/doc-block-source

```mdx
<Source language="html" code={`<some>html</some>`} />
```

You can get very severe runtime performance regressions in storybook. 
The page takes very long time to render and sometimes the tab even crashes.

### To Reproduce

_No response_

### System

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by anchmelev**
Closes #23776

## What I did

Static `<Source code="...">` blocks were subscribing to `SourceContext` updates even though they do not depend on live story snippets. On docs pages with many `Source` blocks, each snippet update could trigger a wave of unnecessary rerenders and repeated syntax-highlighting work.

This change:
- splits the render path so static `code` sources use an empty source context and no longer rerender on unrelated snippet updates
- keeps story-derived `Source` blocks reactive to snippet updates
- adds a regression unit test covering both behaviors
- adds a manual benchmark story to make the regression easy to inspect visually
- replaces the generic `Error` for `of={undefined}` with a typed `StorybookError`

## Benchmark

Local benchmark result:
- Scenario: 75 static `<Source code="...">` blocks
- Trigger: 5 snippet updates
- Before: 375 extra renders
- After: 0 extra renders

## How to verify

1. Run `cd code && yarn storybook:ui`
2. Open `Blocks/Source/ManyStaticCodeBlocksBenchmark`
3. Click `Run 5 updates`
4. Verify the benchmark reports `0 extra renders ...` for static `Source code` blocks
5. Open `Blocks/Source/Of` and verify attached story source still behaves normally

## Summary by CodeRabbit

* **New Features**
  * Added an interactive benchmark story and UI to measure render performance of many static source blocks.

* **Bug Fixes**
  * Consistent, clearer Storybook-specific error reporting when a block’s `of` prop is present but explicitly undefined.

* **Refactor**
  * Preserves explicitly provided code (including empty strings) and bypasses story-derived sources when code is supplied.

* **Tests**
  * Added tests validating Source rerender behavior for static and story-based sources.

### CODE REVIEW

File: code/addons/docs/src/blocks/blocks/Source.tsx [hunk 1]
```diff
@@ -171,11 +174,22 @@ export const useSourceProps = (
...
+  const docsContext = useContext(DocsContext);
+  const sourceProps = useSourceProps(props, docsContext, EMPTY_SOURCE_CONTEXT);
+  return <PureSource {...sourceProps} />;
+};
+
+const SourceImpl = (props: SourceProps) => {
+  const hasCodeProp = props.code !== undefined;
+  return hasCodeProp ? <SourceWithCode {...props} /> : <SourceWithStorySnippet {...props} />;
+};
+
```
Comment (JReinhold) [inline code/addons/docs/src/blocks/blocks/Source.tsx:196]: Could this be greatly simplified to something like this?

```suggestion
const SourceImpl = (props: SourceProps) => {
  const sourceContext = props.code ? EMPTY_SOURCE_CONTEXT : useContext(SourceContext);
  const docsContext = useContext(DocsContext);
  const sourceProps = useSourceProps(props, docsContext, sourceContext);
  return <PureSource {...sourceProps} />;
};

```

So the two different components aren't needed.

File: code/core/src/preview-errors.ts [hunk 2]
```diff
@@ -362,6 +362,17 @@ export class UnknownArgTypesError extends StorybookError {
   }
 }
 
+export class InvalidBlockOfPropError extends StorybookError {
```
Comment (JReinhold) [inline code/core/src/preview-errors.ts:365]: It would be fantastic if you could use this in the other doc blocks too, I believe most of them has the similar pattern, not just Source.

File: code/addons/docs/src/blocks/blocks/Source.stories.tsx [hunk 3]
```diff
@@ -153,3 +288,9 @@ export const Dark: Story = {
 export const CodeDarkParameters: Story = {
   args: { of: ParametersStories.CodeDark },
 };
+
+export const ManyStaticCodeBlocksBenchmark: Story = {
+  render: () => <BenchmarkHarness blocks={75} />,
+  parameters: { chromatic: { disableSnapshot: true } },
+  tags: ['!test', '!vitest'],
```
Comment (JReinhold) [inline code/addons/docs/src/blocks/blocks/Source.stories.tsx]: disabling chromatic makes sense here, but is there a specific reason to disable vitest here?
I was actually looking for the other way around, hoping that there would be a play function for this story that programmatically asserts that the correct amount of re-renders happen. IMO that's also more valuable that manually trying this out, so if that could also mean the story is simplified because it doesn't have to take human QA into account, that would be great.

File: code/addons/docs/src/blocks/blocks/Source.test.tsx
Comment (JReinhold) [inline code/addons/docs/src/blocks/blocks/Source.test.tsx:1]: I don't think we need these tests here, if we can be covered by automated testing the stories instead.

**Review by JReinhold — CHANGES_REQUESTED** [review]
Thanks for the PR! The idea looks good, added a few remarks on the specifics.

File: code/addons/docs/src/blocks/blocks/Source.tsx (hunk 1 above)
Comment (anchmelev) [reply code/addons/docs/src/blocks/blocks/Source.tsx:196]: Great suggestion, thank you. I tried the single-component simplification and ran into two issues:

- The suggested form conditionally calls useContext(SourceContext) (props.code ? ... : useContext(...)), which violates React’s Rules of Hooks because hook call order can change when props.code changes between renders.
- Even with a hooks-safe single-component variant, static <Source code="..."> still subscribed to SourceContext, which regressed the benchmark (ManyStaticCodeBlocksBenchmark) by introducing extra re-renders.

So I kept the behavior-correct split intentionally:

- SourceWithCode uses EMPTY_SOURCE_CONTEXT (no live snippet subscription)
- SourceWithStorySnippet uses SourceContext (live snippet updates)

I also added a benchmark play check to validate this path programmatically.

File: code/core/src/preview-errors.ts (hunk 2 above)
Comment (anchmelev) [reply code/core/src/preview-errors.ts:365]: Great point, thanks! Agreed - I applied the same `InvalidBlockOfPropError` handling across the other docs blocks that already validate explicit `of={undefined}` (ArgTypes, Canvas, Description, Story, Subtitle, Title).

File: code/addons/docs/src/blocks/blocks/Source.stories.tsx (hunk 3 above)
Comment (anchmelev) [reply code/addons/docs/src/blocks/blocks/Source.stories.tsx]: Great point, thank you.
I removed `!vitest` and added a `play` assertion for this benchmark path.
I stabilized the benchmark run for interaction reruns by warming up first and subtracting baseline/background render noise in the harness, so the final assertion remains strict (`0 extra renders ...`) and does not fail on `Rerun` due to runner overhead.

File: code/addons/docs/src/blocks/blocks/Source.test.tsx
Comment (anchmelev) [reply code/addons/docs/src/blocks/blocks/Source.test.tsx:1]: Good point, agreed. I removed `Source.test.tsx`

**Comment by anchmelev** [comment]
> Thanks for the PR! The idea looks good, added a few remarks on the specifics.

Thanks for the review - I really appreciate it. I went through the remarks, addressed them inline, and pushed follow-up changes. Please take another look when you have a chance.

File: code/addons/docs/src/blocks/blocks/Source.stories.tsx [hunk 4]
```diff
@@ -153,3 +304,25 @@ export const Dark: Story = {
 export const CodeDarkParameters: Story = {
   args: { of: ParametersStories.CodeDark },
 };
+
+export const ManyStaticCodeBlocksBenchmark: Story = {
+  render: () => <BenchmarkHarness blocks={75} />,
+  parameters: { chromatic: { disableSnapshot: true } },
+  tags: ['!test'],
```
Comment (JReinhold) [inline code/addons/docs/src/blocks/blocks/Source.stories.tsx]:
```suggestion
```

**Review by JReinhold — APPROVED** [review]

**Comment by anchmelev** [comment]
Hi @JReinhold, thanks again for the approval on this PR.
The follow-up changes from review have been pushed, and the PR should be in good shape now. If there’s anything else you’d like me to adjust, or any remaining threads I should help close out, please let me know. 
Thanks!
