### PR TITLE
Core: Fix composition of storybooks on same origin

### LINKED ISSUE #25957: [Bug]: Local stories not working when loading external refs
### Describe the bug

I'm encountering an issue where the main documentation section of our Storybook project remains indefinitely in the loading state, despite the content having completely loaded. In the video you can see that deleting the `preview-loader` container the content is shown.

https://github.com/storybookjs/storybook/assets/12384231/951c53da-574a-49ff-8dfe-44bcc9c0a4d8

The issue appears to be with how Storybook handles the loading of external references that share the same base URL with the stories loaded externally.

Example of conflicting URLs:

- External ref URL: https://example-storybook.com/components/button/master/
- Storybook base URL: https://example-storybook.com/

The previewInitialized state doesn't get properly updated because the URL matching logic incorrectly impacts the state of an external reference instead of the local story. (see [findRef source code](https://github.com/storybookjs/storybook/blob/44ed235bf675d5b1a0b11706e0f780fdc61e3951/code/lib/manager-api/src/modules/refs.ts#L166)):

``` 
findRef: (source): any => {
      const refs = api.getRefs();
      return Object.values(refs).find(({ url }: any) => url.match(source));
}
```

### To Reproduce

Not the most elegant way but I've prepared a StackBlitz project that mimics a similar configuration. In this example, you can see that the external references match with the same URL, as previously mentioned.

https://stackblitz.com/edit/github-j9db22?file=.storybook%2Fmain.js

note: You may need to update the base url of the ref object.

### System

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ndelangen**
Closes https://github.com/storybookjs/storybook/issues/25957

## What I did

This makes it possible to have refs share the same origin as each other and as well as the main storybook.

This is useful if you have static-storybooks in static directories

#### The changes in this PR are covered in the following automated tests:
- [ ] stories
- [ ] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

What I did was:

- I created a sandbox
- I ran `yarn build-storybook` in the sandbox
- I renamed the `static-storybook` directory to `foo` and copied it into the `static` directory of the sandbox
- I added a ref to the sandboxs `main.ts` file:

```
  refs: {
    'test-component': {
      title: 'test-component',
      url: 'http://localhost:6006/foo/',
    },
  },
```

- I ran `yarn storybook` (dev-mode).
- I was able to observe the preview load correctly
- I was able to switch between the ref and the main
- I able to verify the currect `iframe` was being shown on both routes

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

     - `bug`: Internal changes that fixes incorrect behavior.
     - `maintenance`: User-facing maintenance tasks.
     - `dependencies`: Upgrading (sometimes downgrading) dependencies.
     - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
     - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
     - `documentation`: Documentation **only** changes. Will not show up in release changelog.
     - `feature request`: Introducing a new feature.
     - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
     - `other`: Changes that don't fit in the above categories.
   
   </details>

### 🦋 Canary release

This pull request has been released as version `0.0.0-pr-26304-sha-8cbb06d9`. Try it out in a new sandbox by running `npx storybook@0.0.0-pr-26304-sha-8cbb06d9 sandbox` or in an existing project with `npx storybook@0.0.0-pr-26304-sha-8cbb06d9 upgrade`.
<details>
<summary>More information</summary>

| | |
| --- | --- |
| **Published version** | [`0.0.0-pr-26304-sha-8cbb06d9`](https://npmjs.com/package/@storybook/cli/v/0.0.0-pr-26304-sha-8cbb06d9) |
| **Triggered by** | @ndelangen |
| **Repository** | [storybookjs/storybook](https://github.com/storybookjs/storybook) |
| **Branch** | [`norbert/composition-loading-state-fix`](https://github.com/storybookjs/storybook/tree/norbert/composition-loading-state-fix) |
| **Commit** | [`8cbb06d9`](https://github.com/storybookjs/storybook/commit/8cbb06d941b4ba1d72d7cef80bf4b8f6eeba3464) |
| **Datetime** | Tue Mar  5 14:54:44 UTC 2024 (`1709650484`) |
| **Workflow run** | [8158297657](https://github.com/storybookjs/storybook/actions/runs/8158297657) |

To request a new release of this pull request, mention the `@storybookjs/core` team.

_core team members can create a new canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=26304`_
</details>

### CODE REVIEW

File: code/lib/channels/src/postmessage/getEventSourceUrl.ts [hunk 1]
```diff
@@ -7,6 +7,14 @@ export const getEventSourceUrl = (event: MessageEvent) => {
...
   // This might not be cross-origin safe
   const [frame, ...remainder] = frames.filter((element) => {
+    try {
+      return (
+        element.contentWindow?.location.origin === (event.source as Window).location.origin &&
+        element.contentWindow?.location.pathname === (event.source as Window).location.pathname
+      );
+    } catch (err) {
+      // continue
+    }
```
Comment (ndelangen) [inline code/lib/channels/src/postmessage/getEventSourceUrl.ts:17]: I added this block because when you have 2 iFrames with the same origin, it seems they might share a [WindowProxy](https://developer.mozilla.org/en-US/docs/Glossary/WindowProxy)

I tested this code manually, the `pathname` comparison does the trick.

File: code/lib/manager-api/src/lib/events.ts [hunk 2]
```diff
@@ -19,9 +19,13 @@ export const getEventMetadata = (context: Meta, fullAPI: API) => {
...
-  const ref =
-    refId && fullAPI.getRefs()[refId] ? fullAPI.getRefs()[refId] : fullAPI.findRef(sourceLocation!);
-
+  let ref: API_ComposedRef | undefined;
+  if (refId || sourceType === 'external') {
+    ref =
+      refId && fullAPI.getRefs()[refId]
+        ? fullAPI.getRefs()[refId]
+        : fullAPI.findRef(sourceLocation!);
+  }
```
Comment (ndelangen) [inline code/lib/manager-api/src/lib/events.ts:28]: The bug was here:

`fullAPI.findRef` would match too eagerly. But I found that I could prevent that problem from occurring, by stricter checking and only call `findRef` when `sourceType === 'external'`.

File: code/lib/manager-api/src/modules/refs.ts [hunk 3]
```diff
@@ -75,8 +73,10 @@ export const getSourceType = (source: string, refId?: string) => {
   const { origin: localOrigin, pathname: localPathname } = location;
   const { origin: sourceOrigin, pathname: sourcePathname } = new URL(source);
 
-  const localFull = `${localOrigin + localPathname}`.replace(findFilename, '');
-  const sourceFull = `${sourceOrigin + sourcePathname}`.replace(findFilename, '');
+  const localFull = `${localOrigin + localPathname}`.replace('/iframe.html', '').replace(/\/$/, '');
+  const sourceFull = `${sourceOrigin + sourcePathname}`
+    .replace('/iframe.html', '')
+    .replace(/\/$/, '');
```
Comment (ndelangen) [inline code/lib/manager-api/src/modules/refs.ts:79]: The findFilename regex was complex, and wasn't working well.

Composed storybooks will always look for `iframe.html`, so there's no need for this to be so dynamic.

File: code/lib/manager-api/src/tests/refs.test.ts [hunk 4]
```diff
@@ -25,7 +25,7 @@ vi.mock('@storybook/global', () => {
   // Add additional variations of global.location mock return values in this array.
   // NOTE: The order must match the order that global.location is called in the unit tests.
   const edgecaseLocations = [
-    { origin: 'https://storybook.js.org', pathname: '/storybook/index.html' },
+    { origin: 'https://storybook.js.org', pathname: '/storybook/iframe.html' },
```
Comment (ndelangen) [inline code/lib/manager-api/src/tests/refs.test.ts:28]: This test was simply wrong.

**Review by shilman — APPROVED** [review]
Great job!! 💪
