### PR TITLE
A11y: Improve boolean control contrast in forced colors mode

### LINKED ISSUE #31695: [Bug]: Boolean selection states are not visually distinguishable when using windows high contrast
### Describe the bug

When contrast themes are turned on in windows settings, you cannot tell if booleans are set to true or false.

Image
As seen here, they look almost the same. This is an issue because users with low vision/who rely on contrast themes will not be able to use the storybook controls.

### Reproduction link

https://stackblitz.com/github/storybookjs/sandboxes/tree/next/cra/default-ts/after-storybook?file=src%2FApp.tsx

### Reproduction steps

- go to repro link
- click on the button story
- open windows settings
- in windows settings, go to contrast themes
- select aquatic theme
- to back to the repro link page and observe the control for primary

### System

```bash
Storybook Environment Info:
 
  System:
    OS: Windows 11 10.0.26100
    CPU: (16) x64 AMD EPYC 7763 64-Core Processor
  Binaries:
    Node: 20.18.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.22 - C:\ProgramData\global-npm\yarn.CMD <----- active
    npm: 10.8.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (133.0.3065.92)
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by anchmelev**
Closes #31695

## What I did

- improved the Boolean control styling in forced colors mode so the selected state is clearly distinguishable
- replaced the previous underline-only selected-state treatment with explicit system-color fill, text color, and outline
- hid the native checkbox from visual rendering while preserving semantics and keyboard focus behavior
- added a focused unit test covering the forced-colors style contract

#### The changes in this PR are covered in the following automated tests:

- [ ] stories
- [x] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

1. Run Storybook locally.
2. Open `Boolean Control` docs or `Example/Button -> Primary`.
3. Enable Windows High Contrast mode, or emulate `forced-colors: active` in browser devtools.
4. Verify the selected boolean option is clearly distinguishable from the unselected option.
5. Toggle between `True` and `False` and confirm the highlighted state moves correctly.
6. Confirm no native checkbox artifact is rendered inside the selected segment.

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Release Notes

* **Bug Fixes**
  * Improved focus and outline styling for boolean controls in forced-colors mode
  * Refined hover behavior for boolean control options to remove unnecessary visual effects
  * Enhanced label styling for better accessibility support

* **Tests**
  * Added E2E tests for forced-colors mode behavior
  * Added E2E tests validating focus states and hover interactions

### CODE REVIEW

File: code/addons/docs/src/blocks/controls/Boolean.tsx [hunk 1]
```diff
@@ -26,30 +27,37 @@ const Label = styled.label(({ theme }) => ({
...
+      outline: '1px solid Highlight',
+      outlineOffset: 1,
+    },
+  },
 
   input: {
     appearance: 'none',
-    width: '100%',
-    height: '100%',
+    width: 1,
```
Comment (Sidnioulz) [inline code/addons/docs/src/blocks/controls/Boolean.tsx]: We have a sb-sr-only class, which should be available as a CSSObject too, for when we want to hide content. Though if you change this I encourage you to double check the focus and hover states on the component. Clicking on the label likely still sends focus to the input.

**Review by Sidnioulz — COMMENTED** [review]
Could you please mention the list of browsers used for testing, and if possible, provide screenshots? I've had a bunch of High Contrast Mode PRs in the past where I couldn't reproduce the fix as each browser may choose to use different system colours by default. It helps if I know which browsers were buggy initially! Thanks ❤️

File: code/addons/docs/src/blocks/controls/Boolean.test.tsx
Comment (Sidnioulz) [inline code/addons/docs/src/blocks/controls/Boolean.test.tsx:1]: I don't think we have team conventions on testing CSS (@ghengeveld?), but I'd say it makes a little more sense to me if you mount the component and check the CSS properties it has.

Since we want forced colors, the only tool at our disposal would be Playwright, specifically in `code/e2e-tests/addon-controls.spec.ts`. You could use this to enable forced colors in a specific story and check the resulting CSS in the control's HTML Element:

```ts
await page.emulateMedia({ contrast: 'more' });
```

Comment (Sidnioulz) [reply code/addons/docs/src/blocks/controls/Boolean.test.tsx:1]: If you want to run e2e tests locally
* Install the VSCode playwright extension (easiest method)
* Create a react-vite/default-ts sandbox with `yarn task sandbox`
* Launch it with `cd ../storybook-sandboxes/react-vite-default-ts && yarn storybook`
* Uncomment lines 7 and 8 in `code/playwright.config.ts` to use that SB instance for tests
* Run tests in VSCode

File: code/addons/docs/src/blocks/controls/Boolean.tsx [hunk 2]
```diff
@@ -26,30 +27,37 @@ const Label = styled.label(({ theme }) => ({
       cursor: 'not-allowed',
     },
   },
+  '@media (forced-colors: active)': {
+    background: 'ButtonFace',
+    outline: '1px solid ButtonText',
+  },
+  '&:focus-within': {
+    outline: 'none',
+    boxShadow: `${theme.color.secondary} 0 0 0 1px inset !important`,
```
Comment (Sidnioulz) [inline code/addons/docs/src/blocks/controls/Boolean.tsx]: Question: why do you need to swap the outline for a box-shadow, since you'll redefine the outline in forced-colors?

**Review by Sidnioulz — CHANGES_REQUESTED** [review]
Thanks for the PR! This is a great improvement :)

Image

I'm seeing a side effect when emulation is off: hovering over the inactive option adds an odd border/shadow, which complicates the UI and makes toggle animations look off. We don't need a contrast ratio on hover ([SC 1.4.11](https://www.w3.org/WAI/WCAG21/Understanding/non-text-contrast.html), [G183](https://www.w3.org/WAI/WCAG21/Techniques/general/G183)).

Image

Could you please address that bug and switch the tests to using Playwright? 🙏

File: code/addons/docs/src/blocks/controls/Boolean.tsx (hunk 1 above)
Comment (anchmelev) [reply code/addons/docs/src/blocks/controls/Boolean.tsx]: Agreed. I removed the local visually-hidden style duplication and switched the hidden input to the shared `srOnlyStyles` helper so the Boolean control follows the existing Storybook pattern instead of maintaining its own copy of those rules.

**Comment by anchmelev** [comment]
> Thanks for the PR! This is a great improvement :)
> 
> Image
> I'm seeing a side effect when emulation is off: hovering over the inactive option adds an odd border/shadow, which complicates the UI and makes toggle animations look off. We don't need a contrast ratio on hover ([SC 1.4.11](https://www.w3.org/WAI/WCAG21/Understanding/non-text-contrast.html), [G183](https://www.w3.org/WAI/WCAG21/Techniques/general/G183)).
> 
> Image
> Could you please address that bug and switch the tests to using Playwright? 🙏

Yes, that was a real side effect. I removed the hover shadow from the inactive option in the default mode so the toggle no longer picks up that extra pseudo-border and the selected state remains visually cleaner.

I also tested this in Chrome on Windows 10, and I no longer see this side effect.
image
image

 Please let me know if the issue still reproduces for you after the latest commit. Thanks!

File: code/addons/docs/src/blocks/controls/Boolean.test.tsx
Comment (anchmelev) [reply code/addons/docs/src/blocks/controls/Boolean.test.tsx:1]: Agreed, Playwright is a better fit here than a static style test. I removed the old unit-style test and moved the coverage to `code/e2e-tests/addon-controls.spec.ts`. I also rewrote the checks to go through the existing sandbox-safe `example/button--primary` path instead of relying on a separate docs-block story.

File: code/addons/docs/src/blocks/controls/Boolean.tsx (hunk 2 above)
Comment (anchmelev) [reply code/addons/docs/src/blocks/controls/Boolean.tsx]: Good point, I simplified that as well. The regular focus state now uses `outline` too, while the forced-colors branch keeps the explicit `Highlight` outline override. That makes the behavior more straightforward.

**Comment by anchmelev** [comment]
Hi @Sidnioulz, following up on this PR.
I addressed the requested changes by removing the hover side effect in the default mode, moving the coverage to Playwright, and updating the e2e locator in the latest follow-up commit.
Please let me know if there’s anything else you’d like me to adjust to help move this forward. 
Thanks!

**Review by Sidnioulz — APPROVED** [review]
